### ISSUE TITLE
KML Instance requires DOM Element

### ISSUE THREAD

**Issue by dan-pcces** [windycom/leaflet-kml#1]
Hello!

# Problem

The sample code provided in the readme file indicates that you can load a KML file by providing the file path:

```javascript
var track = new L.KML("assets/example1.kml", {async: true});
```

Running this code throws DOM parsing errors. Looking into the source code, it appears that the KML plugin expects to receive a DOM object rather than a file path. The [original KML plugin](https://github.com/shramov/leaflet-plugins/blob/master/layer/vector/KML.js) had a `loadXML` function which retrieved the DOM object, but this plugin does not seem to have that functionality.

# Suggested Solutions

* Easy option: update the documentation to demonstrate the required retrieval of the DOM object before creating the KML layer. For example:
   ```javascript
        jQuery.get( 'assets/example1.kml' )
          .then( ( kmlDocument ) => {
            var track = new L.KML( kmlDocument, { async: true } )
            this.map.addLayer( track )
          } )
   ```
* Less easy option: update the source code to accept a string, and perform the retrieval on the user's behalf (as in original plugin) to make the documentation valid

Any questions, let me know. Thanks for providing this plugin! :)

Regards,
-- Dan

**Comment by ilblog** [comment]
thx for report

**Comment by ilblog** [comment]
Updated
