### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by shaan1974** [windycom/leaflet-kml#2]
#1
Icons are now always [32,32], it could be great if we can set it as option.

kmlLayer = new L.KML( xml , { iconSize : [37,32] } );

#2

For bind popup it could be great if we can add a dedicate css class and not only the "kml-popup"

Thanks for your work on this usefull plugin.

**Comment by mdorda** [comment]
PR is welcome :-)

**Comment by mdorda** [comment]
Closed due to inactivity.
