### ISSUE TITLE
how do i trigger events like alert or other custom function while clicking in layer

### ISSUE THREAD

**Issue by bjrukin** [windycom/leaflet-kml#20]
I have loaded the layer in the leaflet. but the I want to add click event in the layer.
I didn't find any documentation for this.
Thank you

**Comment by ghost** [comment]
I have the same problem.  There appears to be no way to edit or include additional options in the layer, such as to add minZoom or maxZoom options for the KML layer.   I'm trying to create an option to turn on and off this KML layer, but i'm receiving this error "Control.Layers.js:401 Uncaught TypeError: Cannot read property 'minZoom' of undefined"  How do you define the minZoom and maxZoom in the KML? 

    var weather= fetch('weather.kml').then(res => res.text()).then(kmltext => {
        // Create new kml overlay
        const parser = new DOMParser();
    const kml = parser.parseFromString(kmltext, 'text/xml');
    kml.minZoom = 1;
    const track = new L.KML(kml);
    track.minZoom = 1;
    map.addLayer(track);
    // Adjust map to show the kml
    const bounds = track.getBounds();
    map.fitBounds(bounds);
    });
    weather.minZoom = 1;


var baseLayers = {
        "Grayscale": darkmap,
        "Normal": streets
    };

    var overlays = {
         "Weather": weather,
        "Markers":markers,
    };

    console.log(weather);
    console.log(markers);

    L.control.layers(baseLayers, overlays).addTo(map);

**Comment by mdorda** [comment]
Thank you for your suggestion. We will not implement this functionality, but PR is welcome for this feature if you are interested.
