### ISSUE TITLE
Unable to Customize the KML Layer

### ISSUE THREAD

**Issue by ghost** [windycom/leaflet-kml#22]
There appears to be no way to edit or include additional options in the layer, such as to add minZoom or maxZoom options for the KML layer.   I'm trying to create an option to turn on and off this KML layer, but i'm receiving this error "Control.Layers.js:401 Uncaught TypeError: Cannot read property 'minZoom' of undefined"  How do you define the minZoom and maxZoom in the KML? 

    var map = L.map('map', {
        center: [32.66995747013945, -105.59179687498357],
        maxZoom: 18,
        minZoom: 0,
        zoom: 18,
        layers: [streets,markers]
    });
    map.setView([32.66995747013945, -105.59179687498357], 3);
    var weather= fetch('weather.kml').then(res => res.text()).then(kmltext => {
        // Create new kml overlay
        const parser = new DOMParser();
    const kml = parser.parseFromString(kmltext, 'text/xml');
    kml.minZoom = 1;
    const track = new L.KML(kml);
    track.minZoom = 1;
    map.addLayer(track);
    // Adjust map to show the kml
    const bounds = track.getBounds();
    map.fitBounds(bounds);
    });
    weather.minZoom = 1;

var baseLayers = {
        "Grayscale": darkmap,
        "Normal": streets
    };

    var overlays = {
         "Weather": weather,
        "Markers":markers,
    };

    console.log(weather);
    console.log(markers);

    L.control.layers(baseLayers, overlays).addTo(map);

**Comment by Jorrex** [comment]
I am dealing with the same problem. Due to reorganizing certain layers, using custom panes is a good solution.
But the KML layer is indeed not customizable, so we cannot assign it to a custom pane. It will always be added to the base layer of the map.

**Comment by mdorda** [comment]
Thank you for your suggestion. We will not implement this functionality, but PR is welcome for this feature if you are interested.
