### ISSUE TITLE
Why doesn't Leaflet KML layer plugin work?

### ISSUE THREAD

**Issue by RaffeJaap** [windycom/leaflet-kml#25]
I tried to use Leaflet KML layer plugin but it doesn't show the layer. I first thought it was a problem with my code or my kml, but even when I just copied the code en de example1.kml from https://github.com/windycom/leaflet-kml and used that in an example html, I published it on www.thebestofgeocaching.nl/testmap/testmap.html. But even now only the map showed and not the overlay. What am I doing wrong?

**Comment by RaffeJaap** [comment]
So this is the code I'm using:

<html>
    <head>
        <link rel="stylesheet" href="http://unpkg.com/leaflet@1.4.0/dist/leaflet.css" />
        <script src="http://unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
        <script src="./L.KML.js"></script>
    </head>
    <body>
        <div style="width: 100vw; height: 100vh" id="map"></div>
        <script type="text/javascript">
            // Make basemap
            const map = new L.Map('map', { center: new L.LatLng(37.4, -122.1), zoom: 8 });
            const osm = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');

            map.addLayer(osm);

            // Load kml file
            fetch('./example1.kml')
                .then(res => res.text())
                .then(kmltext => {
                    // Create new kml overlay
                    const parser = new DOMParser();
                    const kml = parser.parseFromString(kmltext, 'text/xml');
                    const track = new L.KML(kml);
                    map.addLayer(track);

                    // Adjust map to show the kml
                    const bounds = track.getBounds();
                    map.fitBounds(bounds);
                });
        </script>
    </body>
</html>

**Comment by Bidwilli** [comment]
I used the same script and had the same issue.  Have you resolved the issue?

**Comment by RaffeJaap** [comment]
No. I'm still hoping someone ...

**Comment by AndPu** [comment]
>The requested URL /thebestofgeocaching/testmap/L.KML.js was not found on this server.

Check URL to L.KML.js and example1.kml
Probably you need copy L.KML.js and example1.kml files to /testmap/ directory and use <script src="L.KML.js"> and fetch('example1.kml')

**Comment by mdorda** [comment]
I just tested it locally and the example works for me. Be sure you included all necessary files, use leaflet 1.4 and ensure your debug console is clear.
