### ISSUE TITLE
KML file download all image and not acting as per minLodPixels values

### ISSUE THREAD

**Issue by lysaan** [windycom/leaflet-kml#26]
An Image should be downloaded when zooming reaches `<minLodPixels>200</minLodPixels>` value but this is not happening.
All images are downloaded when map rendering starts. If there are thousands of images then this is not going to work.
In ideal condition images should be loaded w.r.t map center and zooming level. As it happens in Google Maps.
<br/>
`<Folder> <Region> <LatLonAltBox> <west>174.96510016880586</west> <east>174.99828859706068</east> <south>-37.147368506798173</south> <north>-37.12079474453428</north> </LatLonAltBox> <Lod> <minLodPixels>200</minLodPixels> <maxLodPixels>-1</maxLodPixels> </Lod> </Region> <GroundOverlay> <LatLonBox> <west>174.96510016880586</west> <east>174.99828859706068</east> <south>-37.147368506798173</south> <north>-37.12079474453428</north> </LatLonBox> <drawOrder>1</drawOrder> <Icon> <href>a.png</href> </Icon> </GroundOverlay> <name>a.png</name></Folder>`

**Comment by mdorda** [comment]
Thank you for your suggestion. We will not implement this functionality, but PR is welcome for this feature if you are interested.

**Comment by lysaan** [comment]
We have solved this issue. But our suggestion is that kmz should be extracted on server and then json data should be sent to client end. We have adopted same approach.
