### ISSUE TITLE
why there is no published tags? And can find leaflet-kml#1.0.1 from npm, but here have no this version

### ISSUE THREAD

**Issue by angelZhuzhu** [windycom/leaflet-kml#27]
I want to fetch the code for leaflet-kml#1.0.1.
and actually can find it here: https://www.npmjs.com/package/leaflet-kml/v/1.0.1 .
But can not find the download URL for  leaflet-kml#1.0.1,  could you help this???

**Comment by mdorda** [comment]
This package is not related to the published one. This is a fork.
