### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by PideaLtd** [windycom/leaflet-kml#3]
I'm trying to integrate this into a project so far without success so as a test I thought that I'd impliment the example code shown in the read me file but it doesn't appear to work.

I get a map but no KML is plotted on it (I'm using example2.kml).  I'm not getting any console errors in my browser either.

Can someone confirm that the example in the read me file works ?

**Comment by Krukarius** [comment]
I have got the same problem. I only have a blank map without file at all. All stuff has been implemented correctly so far. 
I am fresh with JS so maybe the fault is on my side. If so, could you explain to me how to use correctly?

**Comment by PideaLtd** [comment]
As I didn't get a reply I moved on and found something else that works.

**Comment by Krukarius** [comment]
Could you send me the link/source? When possible?

Thanks & Regards,

**Comment by PideaLtd** [comment]
There is no source.  I ended up converting my KML files to GeoJSON using this site: https://mygeodata.cloud/converter/kml-to-geojson and then I imported the GeoJSON files into Leaflet using the L.geoJSON(text, callback) function.

GeoJSON files can't contain styling information though so you'll need to add some extra information to your files (I hand edited mine) in the type | Feature | properties section like this:

{ "type": "Feature", "properties": { "Airspace": "Tacan", "Name": "SPT-NAVPI", "description": "" }, "geometry": { "type": "LineString", "coordinates": [ ... ] } }

You'll need a callback function which looks for the corresponding property and then returns the relevant style like this:

function(featurecollection) {
    switch (featurecollection.properties.Airspace) {
        case 'Tacan': return {color: "#FF0000"}; break;
    }
}

Note that KML colours have 4 parts: the alpha channel, then the red, green and blue pairs.  GeoJSON only has the RGB.  I've yet to figure that part out

**Comment by genomexyz** [comment]
I fix the issue of example code of this project, check out my repo in https://github.com/genomexyz/leaflet-kml for the working example

The example code has 2 issues:
1. In the line
`.then( res => response.text() )`
is invalid because the parameter of the arrow function (=>) is res but in function, they called it as response.

2. In the line
`const track = new L.KML(kml)`
They treated kml variable as xml but the truth is, it's just a string. They should parse it as xml beforehand.

**Comment by PideaLtd** [comment]
Excellent, thank you - I shall try this later.

**Comment by mdorda** [comment]
Thanks @genomexyz, I fixed the example.

**Comment by Krukarius** [comment]
Could you clarify how the code should look like? I don't understand these changes enough. I still got a blank map on my example. Thanks

**Comment by mdorda** [comment]
You are right, there was an error with CSS. It is fixed now. I tested it and it works.

![image](https://user-images.githubusercontent.com/6674990/63017289-3f6d2480-be96-11e9-8e8d-cdc25434a1ad.png)
