### ISSUE TITLE
KML layer doesn't seem to work on IE11

### ISSUE THREAD

**Issue by FrancescoFilippi** [windycom/leaflet-kml#5]
## QUESTION:
I'm working with Angular 7 and leaflet, and I'm trying to display KML layers. 
Plugin works fine everywhere but IE11:

- Chrome 76
![Screenshot 2019-08-26 at 11 45 12](https://user-images.githubusercontent.com/9076770/63681983-3a459900-c7f7-11e9-9617-d94ce2832502.png)

- Safari 12.1
![Screenshot 2019-08-26 at 11 58 01](https://user-images.githubusercontent.com/9076770/63682760-f05db280-c7f8-11e9-9187-3a670b329e82.png)

- IE11
![Screenshot 2019-08-26 at 11 45 23](https://user-images.githubusercontent.com/9076770/63682014-4598c480-c7f7-11e9-84d8-d3bb3e02fb96.png)

The code i'm using is pretty standard, i fetch a kml file, decode it and then I add a layer to the map:
```typescript
this.mapService.getFileContents(response.data.kml_url).subscribe( contents => {
    const baseXml = contents;
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(baseXml, 'text/xml');

    const track = new L.KML(xmlDoc, {async: true});
    const bounds = track.getBounds();
    this.map.fitBounds(bounds);
    this.map.addLayer(track);
}
```
Oddly enough, IE11's console shows nothing at all, so I don't really know where to start looking for errors / issues.
Anyone faced the same behaviour?

**Comment by mdorda** [comment]
We do not support IE11. But if I remember it properly, Leaflet had (or still has?) a CSS bug in IE11: the map tiles hide everything inside the map.
